[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.21", features = ["derive"] }
clearscreen = "3.0.0"
image = "0.25.5"
itertools = "0.13.0"
regex = "1.11.1"
rstest = "0.23.0"
